"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False), 
    ALLOWED_HOSTS=(list,[]),
)
environ.Env.read_env(BASE_DIR.parent / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "agent",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db_url("DATABASE_URL"),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# Retrieval / RAG tunables
# ------------------------------------------------------------------
# Embedding model and its output dimensionality. Changing the model
# means re-ingesting the corpus (different vector space) and altering
# the KBChunk.embedding column dimension to match.
EMBEDDING_MODEL = env("EMBEDDING_MODEL", default="BAAI/bge-small-en-v1.5")
EMBEDDING_DIM = env.int("EMBEDDING_DIM", default=384)

# Parent / child chunk window sizes (characters) and the overlap
# both layers use at paragraph boundaries.
KB_PARENT_CHUNK_SIZE = env.int("KB_PARENT_CHUNK_SIZE", default=2048)
KB_CHILD_CHUNK_SIZE = env.int("KB_CHILD_CHUNK_SIZE", default=512)
KB_CHUNK_OVERLAP = env.int("KB_CHUNK_OVERLAP", default=64)

# Reciprocal Rank Fusion: k smooths the score at the head of the
# ranking; weights pick how much to trust semantic vs lexical signal.
KB_RRF_K = env.int("KB_RRF_K", default=60)
KB_SEMANTIC_WEIGHT = env.float("KB_SEMANTIC_WEIGHT", default=0.7)
KB_LEXICAL_WEIGHT = env.float("KB_LEXICAL_WEIGHT", default=0.3)

# Cross-encoder used to rerank an initial candidate list.
KB_RERANKER_MODEL = env(
    "KB_RERANKER_MODEL",
    default="cross-encoder/ms-marco-MiniLM-L-6-v2",
)


# Agent / LLM
# ------------------------------------------------------------------
# LLM_PROVIDER selects the transport in agent/orchestrator/llm_client.py:
# "ollama" hits Ollama's native /api/chat (honours options.num_ctx);
# "openai" uses the OpenAI SDK against OLLAMA_BASE_URL (kept for any
# OpenAI-compatible endpoint, where API key is enforced).
LLM_PROVIDER = env("LLM_PROVIDER", default="ollama")
OLLAMA_BASE_URL = env("OLLAMA_BASE_URL", default="http://localhost:11434/v1")
OLLAMA_API_KEY = env("OLLAMA_API_KEY", default="ollama")
OLLAMA_MODEL = env("OLLAMA_MODEL", default="qwen3.5:9b")

# Context window forwarded to Ollama via the `options` extra. Ollama
# defaults to 4096 regardless of what the model card claims; bump this
# when the synthesis prompt + retrieved chunks risk truncation.
OLLAMA_NUM_CTX = env.int("OLLAMA_NUM_CTX", default=4096)

# Number of KB chunks fed into the synthesis prompt.
AGENT_TOP_K = env.int("AGENT_TOP_K", default=8)

# Cross-encoder reranking. When enabled, hybrid_search returns
# AGENT_TOP_K * AGENT_RERANK_CANDIDATES_MULTIPLIER candidates which
# are then rescored down to AGENT_TOP_K by the reranker.
AGENT_USE_RERANKER = env.bool("AGENT_USE_RERANKER", default=False)
AGENT_RERANK_CANDIDATES_MULTIPLIER = env.int(
    "AGENT_RERANK_CANDIDATES_MULTIPLIER", default=3
)

# Verifier loop: how many synthesis retries before giving up.
AGENT_MAX_VERIFY_RETRIES = env.int("AGENT_MAX_VERIFY_RETRIES", default=2)


# REST framework
# ------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "user": "60/min",
        "anon": "10/min",
    },
    "EXCEPTION_HANDLER": "agent.exception_handler.custom_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}


# Observability
# ------------------------------------------------------------------
# When LANGSMITH_API_KEY is set, LangChain auto-traces every LLM call
# under the configured project name. With no key set the agent runs
# without any external telemetry.
LANGSMITH_API_KEY = env("LANGSMITH_API_KEY", default="")
LANGSMITH_PROJECT = env("LANGSMITH_PROJECT", default="rag-docs-chatbot")
if LANGSMITH_API_KEY:
    os.environ.setdefault("LANGCHAIN_TRACING_V2", "true")
    os.environ.setdefault("LANGCHAIN_API_KEY", LANGSMITH_API_KEY)
    os.environ.setdefault("LANGCHAIN_PROJECT", LANGSMITH_PROJECT)

# Ragas evaluation
# ------------------------------------------------------------------
# Judge LLM used by `ragas_run`. "ollama" reuses the local model
# (free, slower, same model that generated the answer -- biased);
# "openai" routes to the OpenAI API (requires OPENAI_API_KEY, faster
# and more impartial). When RAGAS_JUDGE_MODEL is empty the default is
# OLLAMA_MODEL for ollama or gpt-4o-mini for openai.
RAGAS_JUDGE_PROVIDER = env("RAGAS_JUDGE_PROVIDER", default="ollama")
RAGAS_JUDGE_MODEL = env("RAGAS_JUDGE_MODEL", default="")
OPENAI_API_KEY = env("OPENAI_API_KEY", default="")
