"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import warnings
from datetime import timedelta
from pathlib import Path

import environ
import truststore

# Use the OS certificate store for TLS. Machines behind an SSL-
# inspecting proxy/AV present a CA that certifi does not trust, which
# breaks outbound HTTPS (HuggingFace, Anthropic). The OS store already
# trusts that CA (browsers work), so route Python's TLS through it.
truststore.inject_into_ssl()

# langchain_core, when first imported, force-"surfaces" its own
# (pending) deprecation warnings by prepending a "default" filter for
# them. langgraph then emits one such warning (an allowed_objects
# default we never set ourselves). Importing langchain_core here, then
# overriding with our own ignore filter, keeps that third-party noise
# out of every entry point (settings load before any langgraph import).
import langchain_core  # noqa: F401  (imported for its filter side effect)
from langchain_core._api.deprecation import (
    LangChainDeprecationWarning,
    LangChainPendingDeprecationWarning,
)

warnings.filterwarnings("ignore", category=LangChainPendingDeprecationWarning)
warnings.filterwarnings("ignore", category=LangChainDeprecationWarning)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False), 
    ALLOWED_HOSTS=(list,[]),
)
environ.Env.read_env(BASE_DIR.parent / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "rag",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db_url("DATABASE_URL"),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Cache (DRF throttle counters, shared across gunicorn workers).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://localhost:6379/0"),
    },
}


# Retrieval / RAG tunables
# ------------------------------------------------------------------
# Embedding model and its output dimensionality. Changing the model
# means re-ingesting the corpus (different vector space) and altering
# the KBChunk.embedding column dimension to match.
EMBEDDING_MODEL = env("EMBEDDING_MODEL", default="BAAI/bge-small-en-v1.5")
EMBEDDING_DIM = env.int("EMBEDDING_DIM", default=384)

# Parent / child chunk window sizes (characters) and the overlap
# both layers use at paragraph boundaries.
KB_PARENT_CHUNK_SIZE = env.int("KB_PARENT_CHUNK_SIZE", default=2048)
KB_CHILD_CHUNK_SIZE = env.int("KB_CHILD_CHUNK_SIZE", default=512)
KB_CHUNK_OVERLAP = env.int("KB_CHUNK_OVERLAP", default=64)

# Reciprocal Rank Fusion: k smooths the score at the head of the
# ranking; weights pick how much to trust semantic vs lexical signal.
# Equal weights are plain RRF. A 0.7/0.3 split caps a lexical-only
# candidate at 0.3/(k+1), below the last dense candidate in the pool
# (0.7/(k+2*top_k)), so the lexical channel could reorder dense hits
# but never add a document; on the eval set that cost 2.3pp recall
# at top_k=26 versus equal weights.
KB_RRF_K = env.int("KB_RRF_K", default=60)
KB_SEMANTIC_WEIGHT = env.float("KB_SEMANTIC_WEIGHT", default=0.5)
KB_LEXICAL_WEIGHT = env.float("KB_LEXICAL_WEIGHT", default=0.5)

# Cross-encoder used to rerank an initial candidate list.
KB_RERANKER_MODEL = env(
    "KB_RERANKER_MODEL",
    default="cross-encoder/ms-marco-MiniLM-L-6-v2",
)


# Agent / LLM
# ------------------------------------------------------------------
# LLM_PROVIDER selects the transport in rag/orchestrator/llm_client.py:
# "ollama" hits Ollama's native /api/chat (honours options.num_ctx);
# "openai" uses the OpenAI SDK against OLLAMA_BASE_URL (kept for any
# OpenAI-compatible endpoint, where API key is enforced).
LLM_PROVIDER = env("LLM_PROVIDER", default="ollama")
OLLAMA_BASE_URL = env("OLLAMA_BASE_URL", default="http://localhost:11434/v1")
OLLAMA_API_KEY = env("OLLAMA_API_KEY", default="ollama")
OLLAMA_MODEL = env("OLLAMA_MODEL", default="qwen3.5:9b")

# Context window forwarded to Ollama via the `options` extra. Ollama
# defaults to 4096 regardless of what the model card claims; bump this
# when the synthesis prompt + retrieved chunks risk truncation.
OLLAMA_NUM_CTX = env.int("OLLAMA_NUM_CTX", default=4096)

# Hard cap on generated tokens per LLM call. Without it a model can
# ramble or repeat up to num_ctx on a hard prompt (a multi-hop
# synthesis ran away for minutes); 1024 is ample for a grounded
# answer and bounds worst-case latency.
OLLAMA_NUM_PREDICT = env.int("OLLAMA_NUM_PREDICT", default=1024)

# Number of KB chunks fed into the synthesis prompt. A retrieval-recall
# sweep over the eval set with both channels live puts hybrid recall at
# 88% (8), 90% (12), 98% (26) and 96% (32): the papers dense retrieval
# ranks deep (lora.pdf at 26, attention.pdf at 68 for their multi-hop
# questions) only reach the fused list once the per-channel pool
# (2 * top_k) is wide enough to hold the lexical rank that finds them.
AGENT_TOP_K = env.int("AGENT_TOP_K", default=26)

# Cross-encoder reranking. When enabled, hybrid_search returns
# AGENT_TOP_K * AGENT_RERANK_CANDIDATES_MULTIPLIER candidates which
# are then rescored down to AGENT_TOP_K by the reranker.
AGENT_USE_RERANKER = env.bool("AGENT_USE_RERANKER", default=False)
AGENT_RERANK_CANDIDATES_MULTIPLIER = env.int(
    "AGENT_RERANK_CANDIDATES_MULTIPLIER", default=3
)

# Verifier loop: how many synthesis retries before giving up.
AGENT_MAX_VERIFY_RETRIES = env.int("AGENT_MAX_VERIFY_RETRIES", default=2)

# Split a multi-part question into focused sub-queries, retrieved
# separately and merged round-robin into the same top_k budget.
# Off by default: measured net-negative on this corpus (multi_hop
# recall 83 -> 75%). It fixes questions where one blended query
# buries a topic, but for questions where the single query already
# retrieves both papers, halving the per-query budget drops needed
# chunks. Kept opt-in for corpora with genuinely independent hops.
AGENT_QUERY_DECOMPOSITION = env.bool("AGENT_QUERY_DECOMPOSITION", default=False)


# REST framework
# ------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "user": "60/min",
        "anon": "10/min",
    },
    "EXCEPTION_HANDLER": "rag.exception_handler.custom_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}


# Observability
# ------------------------------------------------------------------
# When LANGSMITH_API_KEY is set, the LangGraph pipeline is traced node
# by node and the @traceable-wrapped LLM client (chat_completion /
# chat_completion_stream) and the retrieve/synthesise/verify nodes
# report their prompts, responses and retrieved context under the
# configured project. With no key set @traceable is a transparent
# pass-through and the pipeline runs without any external telemetry.
LANGSMITH_API_KEY = env("LANGSMITH_API_KEY", default="")
LANGSMITH_PROJECT = env("LANGSMITH_PROJECT", default="rag-docs-chatbot")
# The default LangSmith API host is US; an EU workspace key is
# rejected with 403 there and must point at the EU host instead.
LANGSMITH_ENDPOINT = env("LANGSMITH_ENDPOINT", default="")
if LANGSMITH_API_KEY:
    os.environ.setdefault("LANGCHAIN_TRACING_V2", "true")
    os.environ.setdefault("LANGCHAIN_API_KEY", LANGSMITH_API_KEY)
    os.environ.setdefault("LANGCHAIN_PROJECT", LANGSMITH_PROJECT)
    if LANGSMITH_ENDPOINT:
        os.environ.setdefault("LANGCHAIN_ENDPOINT", LANGSMITH_ENDPOINT)

# Ragas evaluation
# ------------------------------------------------------------------
# Judge LLM used by `ragas_run`:
#   "ollama"    -- local model, free but a weak structured-output
#                  judge (frequent parser failures -> NaN metrics).
#   "openai"    -- OpenAI API (OPENAI_API_KEY), fast and reliable.
#   "anthropic" -- Anthropic API (ANTHROPIC_API_KEY), fast and
#                  reliable; embeddings stay local (no Anthropic
#                  embedding API).
# When RAGAS_JUDGE_MODEL is empty the default is OLLAMA_MODEL for
# ollama, gpt-4o-mini for openai, claude-haiku-4-5 for anthropic.
RAGAS_JUDGE_PROVIDER = env("RAGAS_JUDGE_PROVIDER", default="ollama")
RAGAS_JUDGE_MODEL = env("RAGAS_JUDGE_MODEL", default="")
OPENAI_API_KEY = env("OPENAI_API_KEY", default="")
ANTHROPIC_API_KEY = env("ANTHROPIC_API_KEY", default="")
